TYPE=VIEW
query=select `breezeof_seed`.`buyer_pending_order`.`id` AS `id`,`breezeof_seed`.`user_registration`.`user_registration_id` AS `Buyer_Id`,`breezeof_seed`.`user_registration`.`user_registration_name` AS `Buyer`,`breezeof_seed`.`approved_product`.`product_name` AS `Product`,`breezeof_seed`.`approved_seller`.`approved_seller_id` AS `Seller_Id`,`breezeof_seed`.`approved_seller`.`approved_seller_name` AS `Seller`,`breezeof_seed`.`approved_seller`.`approved_seller_email` AS `Seller_Email`,`breezeof_seed`.`approved_seller`.`approved_seller_contact_no` AS `Seller_Mob`,`breezeof_seed`.`buyer_pending_order`.`price` AS `Price`,`breezeof_seed`.`buyer_pending_order`.`product_quantity_units` AS `Quantity` from (((`breezeof_seed`.`buyer_pending_order` join `breezeof_seed`.`approved_product` on((`breezeof_seed`.`buyer_pending_order`.`product_id` = `breezeof_seed`.`approved_product`.`product_id`))) join `breezeof_seed`.`approved_seller` on((`breezeof_seed`.`approved_product`.`approved_product_seller_id` = `breezeof_seed`.`approved_seller`.`approved_seller_id`))) join `breezeof_seed`.`user_registration` on((`breezeof_seed`.`buyer_pending_order`.`buyer_id` = `breezeof_seed`.`user_registration`.`user_registration_id`)))
md5=6e85e029090f39b1ce2b7514ed80d4e5
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2015-06-18 08:25:04
create-version=1
source=SELECT \n        `buyer_pending_order`.`id` AS `id`,\n        `user_registration`.`user_registration_id` AS `Buyer_Id`,\n        `user_registration`.`user_registration_name` AS `Buyer`,\n        `approved_product`.`product_name` AS `Product`,\n        `approved_seller`.`approved_seller_id` AS `Seller_Id`,\n        `approved_seller`.`approved_seller_name` AS `Seller`,\n        `approved_seller`.`approved_seller_email` AS `Seller_Email`,\n        `approved_seller`.`approved_seller_contact_no` AS `Seller_Mob`,\n        `buyer_pending_order`.`price` AS `Price`,\n        `buyer_pending_order`.`product_quantity_units` AS `Quantity`\n    FROM\n        (((`buyer_pending_order`\n        JOIN `approved_product` ON ((`buyer_pending_order`.`product_id` = `approved_product`.`product_id`)))\n        JOIN `approved_seller` ON ((`approved_product`.`approved_product_seller_id` = `approved_seller`.`approved_seller_id`)))\n        JOIN `user_registration` ON ((`buyer_pending_order`.`buyer_id` = `user_registration`.`user_registration_id`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `breezeof_seed`.`buyer_pending_order`.`id` AS `id`,`breezeof_seed`.`user_registration`.`user_registration_id` AS `Buyer_Id`,`breezeof_seed`.`user_registration`.`user_registration_name` AS `Buyer`,`breezeof_seed`.`approved_product`.`product_name` AS `Product`,`breezeof_seed`.`approved_seller`.`approved_seller_id` AS `Seller_Id`,`breezeof_seed`.`approved_seller`.`approved_seller_name` AS `Seller`,`breezeof_seed`.`approved_seller`.`approved_seller_email` AS `Seller_Email`,`breezeof_seed`.`approved_seller`.`approved_seller_contact_no` AS `Seller_Mob`,`breezeof_seed`.`buyer_pending_order`.`price` AS `Price`,`breezeof_seed`.`buyer_pending_order`.`product_quantity_units` AS `Quantity` from (((`breezeof_seed`.`buyer_pending_order` join `breezeof_seed`.`approved_product` on((`breezeof_seed`.`buyer_pending_order`.`product_id` = `breezeof_seed`.`approved_product`.`product_id`))) join `breezeof_seed`.`approved_seller` on((`breezeof_seed`.`approved_product`.`approved_product_seller_id` = `breezeof_seed`.`approved_seller`.`approved_seller_id`))) join `breezeof_seed`.`user_registration` on((`breezeof_seed`.`buyer_pending_order`.`buyer_id` = `breezeof_seed`.`user_registration`.`user_registration_id`)))
